### ISSUE TITLE
Missing file in data directory.

### ISSUE THREAD

**Issue by laleye** [samehkamaleldin/bio-kge-apps#1]
There is no file named se_map.txt in the data directory. This one being used in pse.py script.

Please can you add it or give a link for download i ?

Thanks

**Comment by samehkamaleldin** [comment]
I have added this file. Check now if it works fine.

**Comment by laleye** [comment]
Thanks,
I will let you know.

**Comment by laleye** [comment]
@samehkamaleldin It works. Thanks
